// Constants
import USERS_MESSAGES from '~/constants/messages'
import HTTP_STATUS from '~/constants/http-status'

export const ErrorMap = {
  USER_NOT_FOUND: {
    message: USERS_MESSAGES.USER_NOT_FOUND,
    status: HTTP_STATUS.NOT_FOUND
  },
  EMAIL_EXISTS: {
    message: USERS_MESSAGES.EMAIL_ALREADY_EXISTS,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  EMAIL_NOT_EXISTS: {
    message: USERS_MESSAGES.EMAIL_DOES_NOT_EXIST,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  PASSWORD_INCORRECT: {
    message: USERS_MESSAGES.PASSWORD_INCORRECT,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  UNAUTHORIZED: {
    message: USERS_MESSAGES.UNAUTHORIZED_ERROR,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  ACCESS_TOKEN_REQUIRED: {
    message: USERS_MESSAGES.ACCESS_TOKEN_REQUIRED,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  INVALID_ACCESS_TOKEN: {
    message: USERS_MESSAGES.INVALID_ACCESS_TOKEN,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  REFRESH_TOKEN_REQUIRED: {
    message: USERS_MESSAGES.REFRESH_TOKEN_REQUIRED,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  INVALID_REFRESH_TOKEN: {
    message: USERS_MESSAGES.INVALID_REFRESH_TOKEN,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: {
    message: USERS_MESSAGES.USED_REFRESH_TOKEN_OR_NOT_EXISTS,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  EMAIL_ALREADY_VERIFIED_BEFORE: {
    message: USERS_MESSAGES.EMAIL_ALREADY_VERIFIED_BEFORE,
    status: HTTP_STATUS.OK
  },
  INVALID_FORGOT_PASSWORD_TOKEN: {
    message: USERS_MESSAGES.INVALID_FORGOT_PASSWORD_TOKEN,
    status: HTTP_STATUS.UNAUTHORIZED
  },
  USER_NOT_VERIFIED: {
    message: USERS_MESSAGES.USER_NOT_VERIFIED,
    status: HTTP_STATUS.FORBIDDEN
  },
  INVALID_USER_ID: {
    message: USERS_MESSAGES.INVALID_USER_ID,
    status: HTTP_STATUS.NOT_FOUND
  },
  CANNOT_FOLLOW_YOURSELF: {
    message: USERS_MESSAGES.CANNOT_FOLLOW_YOURSELF,
    status: HTTP_STATUS.BAD_REQUEST
  },
  CANNOT_UNFOLLOW_YOURSELF: {
    message: USERS_MESSAGES.CANNOT_UNFOLLOW_YOURSELF,
    status: HTTP_STATUS.BAD_REQUEST
  },
  FOLLOWED_USER_NOT_FOUND: {
    message: USERS_MESSAGES.FOLLOWED_USER_NOT_FOUND,
    status: HTTP_STATUS.NOT_FOUND
  },
  ALREADY_FOLLOWED_BEFORE: {
    message: USERS_MESSAGES.ALREADY_FOLLOWED_BEFORE,
    status: HTTP_STATUS.CONFLICT
  },
  ALREADY_UNFOLLOWED_BEFORE: {
    message: USERS_MESSAGES.ALREADY_UNFOLLOWED_BEFORE,
    status: HTTP_STATUS.CONFLICT
  },
  PASSWORD_NOT_MATCH: {
    message: USERS_MESSAGES.PASSWORD_NOT_MATCH,
    status: HTTP_STATUS.BAD_REQUEST
  }
} as const
